/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoffresstage;

/**
 *
 * @author jeremy
 */
public class MenuConsulter extends javax.swing.JFrame {

    /**
     * Creates new form MenuConsulter
     */
    public MenuConsulter() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        txtNomEntreprise.setEditable(false);
        txtVilleStage.setEditable(false);
        txtEmailContact.setEditable(false);
        txtDomaineOffre.setEditable(false);
        txtLibelleOffre.setEditable(false);
        txtDateDebutStage.setEditable(false);
        txtDureeStage.setEditable(false);
        txtaDescriptifOffre.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblConsulterOffresStage = new javax.swing.JLabel();
        lblNomEntreprise = new javax.swing.JLabel();
        txtNomEntreprise = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtVilleStage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmailContact = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDomaineOffre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLibelleOffre = new javax.swing.JTextField();
        lblDateDebutStage = new javax.swing.JLabel();
        txtDateDebutStage = new javax.swing.JTextField();
        lblDureeStage = new javax.swing.JLabel();
        txtDureeStage = new javax.swing.JTextField();
        lblDescriptifOffre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDescriptifOffre = new javax.swing.JTextArea();
        btnPrecedentOffresStage = new javax.swing.JButton();
        btnSuivantOffresStage = new javax.swing.JButton();
        btnFermerOffresStage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lblConsulterOffresStage.setText("CONSULTATION DES OFFRES DE STAGE");

        lblNomEntreprise.setText("Nom de l'entreprise");

        jLabel1.setText("Ville du stage");

        txtVilleStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVilleStageActionPerformed(evt);
            }
        });

        jLabel2.setText("Mail contact");

        jLabel3.setText("Domaine offre");

        jLabel4.setText("Libellé de l'offre");

        txtLibelleOffre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibelleOffreActionPerformed(evt);
            }
        });

        lblDateDebutStage.setText("Date de debut du stage");

        lblDureeStage.setText("Durée du stage");

        txtDureeStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDureeStageActionPerformed(evt);
            }
        });

        lblDescriptifOffre.setText("Descriptif de l'offre");

        txtaDescriptifOffre.setColumns(20);
        txtaDescriptifOffre.setRows(5);
        jScrollPane1.setViewportView(txtaDescriptifOffre);

        btnPrecedentOffresStage.setText("Précédent");

        btnSuivantOffresStage.setText("Suivant");

        btnFermerOffresStage.setText("Fermer");
        btnFermerOffresStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerOffresStageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(lblConsulterOffresStage))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNomEntreprise)
                        .addGap(33, 33, 33)
                        .addComponent(txtNomEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(txtVilleStage, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(txtEmailContact, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDomaineOffre, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLibelleOffre, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDateDebutStage)
                        .addGap(31, 31, 31)
                        .addComponent(txtDateDebutStage, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDureeStage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDureeStage, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblDescriptifOffre)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnPrecedentOffresStage)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuivantOffresStage)
                        .addGap(18, 18, 18)
                        .addComponent(btnFermerOffresStage)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsulterOffresStage)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomEntreprise)
                            .addComponent(txtNomEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtVilleStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtEmailContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtDomaineOffre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtLibelleOffre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDateDebutStage)
                            .addComponent(txtDateDebutStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDureeStage)
                            .addComponent(txtDureeStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrecedentOffresStage)
                            .addComponent(btnSuivantOffresStage)
                            .addComponent(btnFermerOffresStage))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDescriptifOffre)
                        .addGap(88, 88, 88))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVilleStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVilleStageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVilleStageActionPerformed

    private void txtLibelleOffreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibelleOffreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibelleOffreActionPerformed

    private void txtDureeStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDureeStageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDureeStageActionPerformed

    private void btnFermerOffresStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerOffresStageActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFermerOffresStageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuConsulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuConsulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuConsulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuConsulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuConsulter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFermerOffresStage;
    private javax.swing.JButton btnPrecedentOffresStage;
    private javax.swing.JButton btnSuivantOffresStage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConsulterOffresStage;
    private javax.swing.JLabel lblDateDebutStage;
    private javax.swing.JLabel lblDescriptifOffre;
    private javax.swing.JLabel lblDureeStage;
    private javax.swing.JLabel lblNomEntreprise;
    private javax.swing.JTextField txtDateDebutStage;
    private javax.swing.JTextField txtDomaineOffre;
    private javax.swing.JTextField txtDureeStage;
    private javax.swing.JTextField txtEmailContact;
    private javax.swing.JTextField txtLibelleOffre;
    private javax.swing.JTextField txtNomEntreprise;
    private javax.swing.JTextField txtVilleStage;
    private javax.swing.JTextArea txtaDescriptifOffre;
    // End of variables declaration//GEN-END:variables
}
