package projetoffresstage;
import java.util.logging.ConsoleHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import static projetoffresstage.MainProjet.logger;

/**
 *
 * @author jeremy
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GestionOffresStage
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGestionOffresStages = new javax.swing.JPanel();
        btnConsulterOffres = new javax.swing.JButton();
        btnSaisieOffre = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        btnCreerEntreprise = new javax.swing.JButton();
        lblDescartesEtLesPros = new javax.swing.JLabel();
        lblGestionOffresStages = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlGestionOffresStages.setBackground(new java.awt.Color(0, 204, 204));
        pnlGestionOffresStages.setForeground(new java.awt.Color(255, 255, 255));

        btnConsulterOffres.setText("Consulter les offres");
        btnConsulterOffres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulterOffresActionPerformed(evt);
            }
        });

        btnSaisieOffre.setText("Saisir une offre");
        btnSaisieOffre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaisieOffreActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");
        btnAnnuler.setBorderPainted(false);
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        btnCreerEntreprise.setText("Créer une entreprise");
        btnCreerEntreprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreerEntrepriseActionPerformed(evt);
            }
        });

        lblDescartesEtLesPros.setForeground(new java.awt.Color(255, 255, 255));
        lblDescartesEtLesPros.setText("Descartes&LesPros");

        lblGestionOffresStages.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionOffresStages.setText("GESTION DES OFFRES DE STAGES");

        javax.swing.GroupLayout pnlGestionOffresStagesLayout = new javax.swing.GroupLayout(pnlGestionOffresStages);
        pnlGestionOffresStages.setLayout(pnlGestionOffresStagesLayout);
        pnlGestionOffresStagesLayout.setHorizontalGroup(
            pnlGestionOffresStagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGestionOffresStagesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGestionOffresStages)
                .addGap(207, 207, 207))
            .addGroup(pnlGestionOffresStagesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGestionOffresStagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDescartesEtLesPros)
                    .addGroup(pnlGestionOffresStagesLayout.createSequentialGroup()
                        .addComponent(btnCreerEntreprise)
                        .addGap(54, 54, 54)
                        .addGroup(pnlGestionOffresStagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaisieOffre))
                        .addGap(38, 38, 38)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsulterOffres)
                .addGap(35, 35, 35))
        );
        pnlGestionOffresStagesLayout.setVerticalGroup(
            pnlGestionOffresStagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGestionOffresStagesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblGestionOffresStages)
                .addGap(18, 18, 18)
                .addComponent(lblDescartesEtLesPros)
                .addGap(51, 51, 51)
                .addGroup(pnlGestionOffresStagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreerEntreprise)
                    .addComponent(btnSaisieOffre)
                    .addComponent(btnConsulterOffres))
                .addGap(64, 64, 64)
                .addComponent(btnAnnuler)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGestionOffresStages, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlGestionOffresStages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreerEntrepriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreerEntrepriseActionPerformed
        MainProjet.logger.info("On a cliqué sur le bouton de création d'entreprise !");
        MainProjet.logger.entering(MainProjet.class.getName(),"btnEnvoyerActionPerformed");
        MenuCreationEntreprise a = new MenuCreationEntreprise();
        a.setVisible(true);
        
        //logger.setLevel(Level.FINER);
    }//GEN-LAST:event_btnCreerEntrepriseActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        MainProjet.logger.info("On a arrêté l'application !");
        System.exit(0);
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnSaisieOffreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaisieOffreActionPerformed
        MenuSaisie s = new MenuSaisie();
        s.setVisible(true);
        
        //logger.setLevel(Level.FINER);
    }//GEN-LAST:event_btnSaisieOffreActionPerformed

    private void btnConsulterOffresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulterOffresActionPerformed
        MenuConsulter c = new MenuConsulter();
        c.setVisible(true);
        
        //logger.setLevel(Level.FINER);
    }//GEN-LAST:event_btnConsulterOffresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnConsulterOffres;
    private javax.swing.JButton btnCreerEntreprise;
    private javax.swing.JButton btnSaisieOffre;
    private javax.swing.JLabel lblDescartesEtLesPros;
    private javax.swing.JLabel lblGestionOffresStages;
    private javax.swing.JPanel pnlGestionOffresStages;
    // End of variables declaration//GEN-END:variables
}
