package projetoffresstage;

import javax.swing.JOptionPane;
import static projetoffresstage.MainProjet.lesEntreprises;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jeremy
 */
public class MenuCreationEntreprise extends javax.swing.JFrame {

    /**
     * Creates new form MenuCreationEntreprise
     */
    public MenuCreationEntreprise() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCreationEntreprise = new javax.swing.JLabel();
        lblNomEntreprise = new javax.swing.JLabel();
        txtNomEntreprise = new javax.swing.JTextField();
        lblNumeroRue = new javax.swing.JLabel();
        lblCodePostal = new javax.swing.JLabel();
        lblVille = new javax.swing.JLabel();
        lblMailContact = new javax.swing.JLabel();
        lblTelephoneContact = new javax.swing.JLabel();
        lblSecteurActiviteEntrprise = new javax.swing.JLabel();
        txtAdresseNumeroRue = new javax.swing.JTextField();
        txtCodePostal = new javax.swing.JTextField();
        txtVille = new javax.swing.JTextField();
        txtMailContact = new javax.swing.JTextField();
        txtTelephoneContact = new javax.swing.JTextField();
        txtSecteurActiviteEntreprise = new javax.swing.JTextField();
        btnEnvoyer = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 102));

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));

        lblCreationEntreprise.setText("CREATION D'UNE ENTREPRISE");

        lblNomEntreprise.setText("Nom de L'entreprise : ");

        lblNumeroRue.setText("Adress (numéro et rue) : ");

        lblCodePostal.setText("Adresse (code postal) : ");

        lblVille.setText("Adresse (ville) : ");

        lblMailContact.setText("Mail du contact : ");

        lblTelephoneContact.setText("Téléphone du contact : ");

        lblSecteurActiviteEntrprise.setText("Secteur d'activité de l'entreprise : ");

        txtAdresseNumeroRue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdresseNumeroRueActionPerformed(evt);
            }
        });

        btnEnvoyer.setText("Envoyer");
        btnEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvoyerActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCreationEntreprise)
                .addGap(132, 132, 132))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEnvoyer)
                    .addComponent(lblSecteurActiviteEntrprise)
                    .addComponent(lblTelephoneContact)
                    .addComponent(lblMailContact)
                    .addComponent(lblVille)
                    .addComponent(lblCodePostal)
                    .addComponent(lblNumeroRue)
                    .addComponent(lblNomEntreprise))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMailContact)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdresseNumeroRue, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelephoneContact, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSecteurActiviteEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnnuler))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblCreationEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblNomEntreprise))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroRue)
                    .addComponent(txtAdresseNumeroRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodePostal)
                    .addComponent(txtCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVille)
                    .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMailContact)
                    .addComponent(txtMailContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelephoneContact)
                    .addComponent(txtTelephoneContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSecteurActiviteEntrprise)
                    .addComponent(txtSecteurActiviteEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnvoyer)
                    .addComponent(btnAnnuler))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdresseNumeroRueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdresseNumeroRueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdresseNumeroRueActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        MainProjet.logger.exiting(MainProjet.class.getName(), "btnAnnulerActionPerformed");
        this.dispose();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvoyerActionPerformed
        
        if(this.txtNomEntreprise.getText().compareTo("") != 0 && this.txtAdresseNumeroRue.getText().compareTo("") != 0 && this.txtCodePostal.getText().compareTo("") != 0 && this.txtVille.getText().compareTo("") != 0 && this.txtMailContact.getText().compareTo("") != 0 && this.txtTelephoneContact.getText().compareTo("") != 0 && this.txtSecteurActiviteEntreprise.getText().compareTo("") != 0)
        {
            String nomEntreprise = "";
            String rueEntreprise = "";
            String cpEntreprise = "";
            String villeEntreprise = "";
            String emailEntreprise = "";
            String telEntreprise = "";
            String secteurActiviteEntreprise = "";
            boolean error = false;
            
            // Nom de l'entreprise
            try
            {
                nomEntreprise = txtNomEntreprise.getText();
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null,"Le nom est invalide !","Création Entreprise",1);
                error = true;
            }
            
            // Rue de l'entreprise
            try
            {
                rueEntreprise = txtAdresseNumeroRue.getText();
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null,"La rue est invalide !","Création entreprise",1);
                error = true;
            }
            
            // Code postal de l'entreprise
            try
            {
                cpEntreprise = txtCodePostal.getText();
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null,"Le code postal est invalide !","Création entreprise",1);
                error = true;
            }
            
            // Ville de l'entreprise
            try
            {
                villeEntreprise = txtVille.getText();
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null,"La ville est invalide !","Création entreprise",1);
                error = true;
            }
            
            // L'adresse email de l'entreprise
            try
            {
                emailEntreprise = txtMailContact.getText();
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null,"L'email est invalide !","Création entreprise",1);
                error = true;
            }
            
            // Numéro de téléphone de l'entreprise
            try
            {
                telEntreprise = this.txtTelephoneContact.getText();
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null,"Le numéro de téléphone est invalide !","Création entreprise",1);
                error = true;
            }
            
            // Secteur d'activité de l'entreprise
            try
            {
                secteurActiviteEntreprise = txtSecteurActiviteEntreprise.getText();
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null,"Le secteur d'activité est invalide !","Création entreprise",1);
                error = true;
            }
            
            // Longueur du code postal de l'entreprise
            if(cpEntreprise.length() < 5)
            {
                JOptionPane.showMessageDialog(null,"Le code postal est invalide !","Création entreprise",1);
                error = true;
            }
            
            // Longueur du numéro de téléphone l'entreprise
            if(telEntreprise.length() < 10)
            {
                JOptionPane.showMessageDialog(null,"Le numéro de téléphone est invalide !","Création entreprise",1);
                error = true;
            }

            // Si aucune erreur de saisie n'est détéctée
            if(!error)
            {
                System.out.println("ajout");
                //Entreprise e = new Entreprise(nomEntreprise, rueEntreprise, cpEntreprise, villeEntreprise, emailEntreprise, telEntreprise, secteurActiviteEntreprise);
                MainProjet.lesEntreprises.add(new Entreprise(nomEntreprise, 
                                                  rueEntreprise, 
                                                  cpEntreprise, 
                                                  villeEntreprise, 
                                                  emailEntreprise, 
                                                  telEntreprise, 
                                                  secteurActiviteEntreprise));
                JOptionPane.showMessageDialog(null,"entreprise crée" ,"Création entreprise",1);
                //JOptionPane.showMessageDialog(null,"Entreprise crée","Création entreprise",1);
                this.dispose();
            
                
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Veuillez remplir tous les champs !","Création Propriétaire",1);
        }
       
    }//GEN-LAST:event_btnEnvoyerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCreationEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCreationEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCreationEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCreationEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCreationEntreprise().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnEnvoyer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodePostal;
    private javax.swing.JLabel lblCreationEntreprise;
    private javax.swing.JLabel lblMailContact;
    private javax.swing.JLabel lblNomEntreprise;
    private javax.swing.JLabel lblNumeroRue;
    private javax.swing.JLabel lblSecteurActiviteEntrprise;
    private javax.swing.JLabel lblTelephoneContact;
    private javax.swing.JLabel lblVille;
    private javax.swing.JTextField txtAdresseNumeroRue;
    private javax.swing.JTextField txtCodePostal;
    private javax.swing.JTextField txtMailContact;
    private javax.swing.JTextField txtNomEntreprise;
    private javax.swing.JTextField txtSecteurActiviteEntreprise;
    private javax.swing.JTextField txtTelephoneContact;
    private javax.swing.JTextField txtVille;
    // End of variables declaration//GEN-END:variables
}
